import Head from 'next/head';
import { useMDXComponent } from 'next-contentlayer/hooks';
import { allPosts, type Post } from 'contentlayer/generated';
import { compareDesc } from 'date-fns';

const posts = allPosts.sort((a, b) => {
  return compareDesc(new Date(a.date), new Date(b.date));
});

export const getStaticPaths = async () => {
  return {
    paths: posts.map((item) => {
      return { params: { slug: item.url } };
    }),
    fallback: false,
  };
};

export const getStaticProps = async () => {
  // const foundIndex = posts.findIndex((post) => post.slug === params.slug.join('/'));

  const post = posts[0];

  // rss

  return { props: { post } };
};

export default function Home({ post }: { post: Post }) {
  const MDXContent = useMDXComponent(post.body.code);
  return (
    <>
      <Head>
        <title>文章</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <article className='container mx-auto prose  p-6'>
        <MDXContent />
      </article>
    </>
  );
}
