import Head from 'next/head';
import { useMDXComponent } from 'next-contentlayer/hooks';
import { allPosts, type Post } from 'contentlayer/generated';

export const getStaticPaths = async () => {
  return {
    paths: allPosts.map((item) => {
      return { params: { slug: item.url } };
    }),
    fallback: false,
  };
};

export const getStaticProps = async ({ params }: any) => {
  const foundIndex = allPosts.findIndex((post) => post.url === params.slug);
  const post = allPosts[foundIndex];
  return { props: { post } };
};

export default function Home({ post }: { post: Post }) {
  const MDXContent = useMDXComponent(post.body.code);
  return (
    <>
      <Head>
        <title>文章</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <article className='container mx-auto prose  p-6'>
        <MDXContent />
      </article>
    </>
  );
}
